#ifndef _GRENDER_SHADERS_H_
#define _GRENDER_SHADERS_H_

/**
 * WGSL for both draw passes. Everything is vertex-pulled from storage buffers:
 * nodes and edges are drawn as instanced quads (6 vertices, 2 triangles) with
 * no vertex buffers, so a frame is exactly two draw calls regardless of graph
 * size. Layout must match grGlobalsUBO and the bind group in grRenderer.c.
 */
static const char GR_WGSL_SOURCE[] =
    "struct Globals {\n"
    "  viewProj   : mat4x4f,\n"
    "  camRight   : vec4f,\n"
    "  camUp      : vec4f,\n"
    "  viewport   : vec2f,\n"
    "  posDim     : u32,\n"
    "  flags      : u32,\n"
    "  nodeFill   : vec4f,\n"
    "  nodeStroke : vec4f,\n"
    "  nodeParams : vec4f,\n" // x radius, y strokeWidth, z sizeMode, w proj11
    "  edgeColor  : vec4f,\n"
    "  edgeParams : vec4f,\n" // x width, y sizeMode
    "}\n"
    "\n"
    "const FLAG_NODE_COLORS : u32 = 1u;\n"
    "const FLAG_NODE_SIZES  : u32 = 2u;\n"
    "const FLAG_EDGE_COLORS : u32 = 4u;\n"
    "\n"
    "@group(0) @binding(0) var<uniform> G : Globals;\n"
    "@group(0) @binding(1) var<storage, read> positions  : array<f32>;\n"
    "@group(0) @binding(2) var<storage, read> nodeIds    : array<u32>;\n"
    "@group(0) @binding(3) var<storage, read> nodeColors : array<u32>;\n"
    "@group(0) @binding(4) var<storage, read> nodeSizes  : array<f32>;\n"
    "@group(0) @binding(5) var<storage, read> edges      : array<u32>;\n"
    "@group(0) @binding(6) var<storage, read> edgeColors : array<u32>;\n"
    "\n"
    "fn getPos(i : u32) -> vec3f {\n"
    "  let base = i * G.posDim;\n"
    "  var p = vec3f(positions[base], positions[base + 1u], 0.0);\n"
    "  if (G.posDim >= 3u) { p.z = positions[base + 2u]; }\n"
    "  return p;\n"
    "}\n"
    "\n"
    // Screen pixels covered by one world unit at clip-space depth w.
    "fn pxPerWorld(clipW : f32) -> f32 {\n"
    "  return G.nodeParams.w * G.viewport.y / (2.0 * max(clipW, 1e-6));\n"
    "}\n"
    "\n"
    "fn unpackColor(c : u32) -> vec4f {\n"
    "  return vec4f(\n"
    "    f32(c & 0xFFu) / 255.0,\n"
    "    f32((c >> 8u) & 0xFFu) / 255.0,\n"
    "    f32((c >> 16u) & 0xFFu) / 255.0,\n"
    "    f32((c >> 24u) & 0xFFu) / 255.0);\n"
    "}\n"
    "\n"
    // Quad corners for two CCW triangles.
    "const CORNERS = array<vec2f, 6>(\n"
    "  vec2f(-1.0, -1.0), vec2f(1.0, -1.0), vec2f(1.0, 1.0),\n"
    "  vec2f(-1.0, -1.0), vec2f(1.0, 1.0), vec2f(-1.0, 1.0));\n"
    "\n"
    // ---------------------------------------------------------------- nodes --
    "struct NodeOut {\n"
    "  @builtin(position) clip : vec4f,\n"
    "  @location(0) local : vec2f,\n"      // px offset from node center
    "  @location(1) fill : vec4f,\n"
    "  @location(2) @interpolate(flat) radiusPx : f32,\n"
    "  @location(3) @interpolate(flat) strokePx : f32,\n"
    "}\n"
    "\n"
    "@vertex\n"
    "fn vsNode(@builtin(vertex_index) vid : u32,\n"
    "          @builtin(instance_index) iid : u32) -> NodeOut {\n"
    "  let corner = CORNERS[vid];\n"
    "  let id = nodeIds[iid];\n"
    "  var clip = G.viewProj * vec4f(getPos(id), 1.0);\n"
    "\n"
    "  var radius = G.nodeParams.x;\n"
    "  if ((G.flags & FLAG_NODE_SIZES) != 0u) { radius = nodeSizes[id]; }\n"
    "  var radiusPx = radius;\n"
    "  if (G.nodeParams.z > 0.5) { radiusPx = radius * pxPerWorld(clip.w); }\n"
    "  let strokePx = select(G.nodeParams.y,\n"
    "                        G.nodeParams.y * pxPerWorld(clip.w),\n"
    "                        G.nodeParams.z > 0.5);\n"
    "\n"
    // 1px feather margin so antialiasing is never clipped by the quad.
    "  let quadPx = radiusPx + strokePx + 1.0;\n"
    "  let local = corner * quadPx;\n"
    "  clip = vec4f(clip.xy + local * 2.0 / G.viewport * clip.w, clip.zw);\n"
    "\n"
    "  var fill = G.nodeFill;\n"
    "  if ((G.flags & FLAG_NODE_COLORS) != 0u) {\n"
    "    fill = unpackColor(nodeColors[id]);\n"
    "  }\n"
    "  return NodeOut(clip, local, fill, radiusPx, strokePx);\n"
    "}\n"
    "\n"
    "@fragment\n"
    "fn fsNode(in : NodeOut) -> @location(0) vec4f {\n"
    "  let dist = length(in.local);\n"
    "  let outer = in.radiusPx + in.strokePx;\n"
    "  let coverage = 1.0 - smoothstep(outer - 1.0, outer, dist);\n"
    "  if (coverage <= 0.0) { discard; }\n"
    "  var color = in.fill;\n"
    "  if (in.strokePx > 0.0) {\n"
    "    let t = smoothstep(in.radiusPx - 0.5, in.radiusPx + 0.5, dist);\n"
    "    color = mix(in.fill, G.nodeStroke, t);\n"
    "  }\n"
    "  return vec4f(color.rgb, color.a * coverage);\n"
    "}\n"
    "\n"
    // ---------------------------------------------------------------- edges --
    "struct EdgeOut {\n"
    "  @builtin(position) clip : vec4f,\n"
    "  @location(0) across : f32,\n"         // signed px across the edge
    "  @location(1) color : vec4f,\n"
    "  @location(2) @interpolate(flat) halfWidthPx : f32,\n"
    "}\n"
    "\n"
    "@vertex\n"
    "fn vsEdge(@builtin(vertex_index) vid : u32,\n"
    "          @builtin(instance_index) iid : u32) -> EdgeOut {\n"
    "  let a = edges[iid * 2u];\n"
    "  let b = edges[iid * 2u + 1u];\n"
    "  var clipA = G.viewProj * vec4f(getPos(a), 1.0);\n"
    "  var clipB = G.viewProj * vec4f(getPos(b), 1.0);\n"
    // Clamp w to keep endpoints behind a perspective camera from exploding.
    "  clipA.w = max(clipA.w, 1e-4);\n"
    "  clipB.w = max(clipB.w, 1e-4);\n"
    "\n"
    "  let screenA = clipA.xy / clipA.w * G.viewport * 0.5;\n"
    "  let screenB = clipB.xy / clipB.w * G.viewport * 0.5;\n"
    "  var dir = screenB - screenA;\n"
    "  let len = length(dir);\n"
    "  if (len < 1e-6) { dir = vec2f(1.0, 0.0); } else { dir = dir / len; }\n"
    "  let normal = vec2f(-dir.y, dir.x);\n"
    "\n"
    // vid 0..5 -> (end, side): triangles (A-,B-,B+),(A-,B+,A+)
    "  var end = 0.0;\n"
    "  if (vid == 1u || vid == 2u || vid == 4u) { end = 1.0; }\n"
    "  var side = -1.0;\n"
    "  if (vid == 2u || vid == 4u || vid == 5u) { side = 1.0; }\n"
    "\n"
    "  let clipEnd = mix(clipA, clipB, end);\n"
    "  var halfWidthPx = G.edgeParams.x * 0.5;\n"
    "  if (G.edgeParams.y > 0.5) {\n"
    "    halfWidthPx = halfWidthPx * pxPerWorld(clipEnd.w);\n"
    "  }\n"
    // Half-pixel feather margin.
    "  let quadHalf = halfWidthPx + 0.5;\n"
    "  let screen = mix(screenA, screenB, end) + normal * side * quadHalf;\n"
    "  let clip = vec4f(screen * 2.0 / G.viewport * clipEnd.w, clipEnd.zw);\n"
    "\n"
    "  var color = G.edgeColor;\n"
    "  if ((G.flags & FLAG_EDGE_COLORS) != 0u) {\n"
    "    color = unpackColor(edgeColors[iid]);\n"
    "  }\n"
    "  return EdgeOut(clip, side * quadHalf, color, halfWidthPx);\n"
    "}\n"
    "\n"
    "@fragment\n"
    "fn fsEdge(in : EdgeOut) -> @location(0) vec4f {\n"
    "  let coverage =\n"
    "      1.0 - smoothstep(in.halfWidthPx - 0.5, in.halfWidthPx + 0.5,\n"
    "                       abs(in.across));\n"
    "  if (coverage <= 0.0) { discard; }\n"
    "  return vec4f(in.color.rgb, in.color.a * coverage);\n"
    "}\n";

#endif
